[build]
  command = "npm run build && cp -r oasis dist/oasis"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/oasis/:splat"
  status = 200
  force = true
  [redirects.conditions]
    Host = ["oasis.famjamevents.com"]
